### ISSUE TITLE
JS for Browser compatibility

### ISSUE THREAD

**Issue by WisdomSky** [Salamek/huawei-lte-api-ts#22]
It seems importing this package on a web project doesn't seem to work. It fails since it uses NodeJS-only APIs.

I'm wondering if we can adjust this so that we can make it work on using JS for browsers?

**Comment by Salamek** [comment]
Hi, i had a looong look on this, i was able to implement webpack to build browser compatible bundle (dist.browser folder):

* I had to update `axios` and `axios-cookiejar-support` to work with browser/webpack whoever
* I had to solve CORS issues since my huawei router does not set any `Access-Control-Allow-Origin` headers and its cookies are not allowed for CrossSite, this meant implementing custom proxy server in `examples/web_proxy/index.js` that adds correct `Access-Control-Allow-Origin` headers to all responses and adds `SameSite=None;Secure;` to all `Set-Cookie` headers without this you won't be able to make requests from browser to router (in my case B310-22s)
* I added example html file in examples/browser.html that prints router info


Sadly all this is not usable without that proxy server, so you still need to run your own webserver/proxy^ (or somehow flash your web project into your Huawei LTE Modem lol)
